### PR TITLE
Export types from main entry-point

### LINKED ISSUE #10: Type `PositionLike` no longer exported
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unist-util-position@4,0.4

### Link to runnable example

_No response_

### Steps to reproduce

Add `react-markdown` to a TS project with `skipLibCheck` set to `false`.

### Expected behavior

No type errors in the declaration files.

### Actual behavior

```
ERROR in node_modules/mdast-util-to-hast/lib/index.d.ts:25:58
TS2694: Namespace '"node_modules/unist-util-position/index"' has no exported member 'PositionLike'.
    23 | export type Element = import('hast').Element
    24 | export type Content = import('hast').ElementContent
  > 25 | export type PositionLike = import('unist-util-position').PositionLike
       |                                                          ^^^^^^^^^^^^
    26 | export type EmbeddedHastFields = {
    27 |   /**
    28 |    * Defines the tag name of an element.
```

### Affected runtime and version

N/A

### Affected package manager and version

_No response_

### Affected OS and version

_No response_

### Build and bundle tools

_No response_

### PR DESCRIPTION
**Pull request by Methuselah96**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Fixes #10.
Export packages types from the main entry-point.

### CODE REVIEW

**Review by ChristianMurphy — COMMENTED** [review]
Thanks for looking into this @Methuselah96!
I appreciate you!

@wooorm was this change intentional? It looks like https://github.com/syntax-tree/unist-util-position/commit/d23f8082476fd5f850507253e391eeb18ea3588a may have intentionally made this interface private?

I'm good either way, just want to check the intent before signing off.

**Comment by wooorm** [comment]
It's intentional. It was never supposed to be exposed. It's also not documented (it's instead mention explicitly that there are no types exported).

Why do you need this type? Why not use a Node interface from mdast or hast?

**Comment by wooorm** [comment]
Ahh OK it's mdast-util-to-hast that needs a fix!

**Comment by wooorm** [comment]
Thanks, fixed

**Pull request closed without merging**
